// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with the Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36RhA4wnCsABAcKGHbmwnjnFyxqWmqFU',
    appId: '1:342192215224:web:eb354bbff95c2a5027d04d',
    messagingSenderId: '342192215224',
    projectId: 'exponomade-87d35',
    authDomain: 'exponomade-87d35.firebaseapp.com',
    storageBucket: 'exponomade-87d35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYER_KgdSGltPTUIRp0PIKsWDSi9gNhh4',
    appId: '1:342192215224:android:3180cefe1360dab027d04d',
    messagingSenderId: '342192215224',
    projectId: 'exponomade-87d35',
    storageBucket: 'exponomade-87d35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7FkG7vUt1X67z9vIErQ0rOwUlrOv6Qg',
    appId: '1:342192215224:ios:892a506b1070667a27d04d',
    messagingSenderId: '342192215224',
    projectId: 'exponomade-87d35',
    storageBucket: 'exponomade-87d35.appspot.com',
    iosClientId: '342192215224-bhvh1ch2ri96chgeqi7laslps6fk810l.apps.googleusercontent.com',
    iosBundleId: 'com.example.exponomade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7FkG7vUt1X67z9vIErQ0rOwUlrOv6Qg',
    appId: '1:342192215224:ios:aff2c0fd19254a5b27d04d',
    messagingSenderId: '342192215224',
    projectId: 'exponomade-87d35',
    storageBucket: 'exponomade-87d35.appspot.com',
    iosClientId: '342192215224-0j3lfjp6774pagkmsgfcf29r5e9mi2so.apps.googleusercontent.com',
    iosBundleId: 'com.example.exponomade.RunnerTests',
  );
}
